const bio = [
  "I am a mid-level Software Engineer with experience in full-stack development, DevOps, Database Management, PEGA, managing and creating external correspondence, adhering to client design artifacts and mockups, adhering to web accessibility compliance standards, and network system administration.",
  `My technical skills are complemented by strategic planning and project leadership for clients' web-based and network solutions needs.`,
  "My passion in software is driven by the many ways there are solves the problems presented. The ability to experiment with what works to solve problems keeps things fresh and interesting. Especially when reviewing past solutions to optimize them. I also enjoy how there is always something new to learn in software and coding. It's an ever-changing field and I am happy to be a part of it.",
  "I am capable of quickly learning as proven by attending and graduating a 6 month, 1000+ hour coding bootcamp. These skills have carried over into my career as I have been able to effortlessly learn and adapt to new and ever evolving languages, platforms, and softwares I use on a day to day basis. I have also been able to easily adapt to the needs of my team and the clients' needs when it comes to introducing new technologies, softwares, frameworks, coding languages, or to cross-train to aide my colleagues with their tasks and needs.",
  "My personal interests, knowledge, and experience include cloud services and containerization (Docker and Kubernetes). I have set up a few devices as a homelab with each one running Ubuntu Server with services and software running inside Docker containers. These are used to fulfil my personal needs and include services and softwares such as: NGINX, DDNS, a media server, a local password manager, a game server hosting platform, a personal cloud server, a VPN to access the local network externally, and a local DNS filtering server. The servers and all individual containers are constantly monitored and backed up.",
  "I would love to break into the cybersecurity sector. Some of my dreams and passions with cybersecurity include making IoT devices more secure for both consumer and enterprise users without advanced knowledge and configures along with wanting to develop and architect new standards for securely storing personal information such as medical records."
];
// const bio = [
//   "I am a creative, fast learning, and problem solving software engineer aspiring to make the web more safe, secure, accessible, and privacy focused. I am excited to start my software engineering career using the knowledge and skills I have quickly learned from the 6 month, 1000+ hour coding course where I was taught the fundamentals of JavaScript, TypeScript, MongoDB, PostgreSQL, and how to build an app from the ground up with React and React frameworks as well as the importance of accessibility (A11y & W3 compliance) online and in apps. In fact, this website is A11y and W3 complaint.",
//   "I've had a passion for technology since I was young and built my first website in high school using a Joomla!. Watching my ideas come to life before my eyes, where people were 1 tap or click away form seeing it, is what led me to eventually pursue a career in web development and software engineering.",
//   "Solving the challenges and problems presented to me through my coursework was extremely rewarding. I'm enthralled by the thought of taking these skills and translating them into solving real world problems. Especially if I am doing that throughout my entire career.",
//   "What I love the most about software engineering is there are always many ways to solve the problems presented to you. Having to come up with your own idea to solve them keeps things fresh and interesting. Especially reviewing your past solutions to optimize them.",
//   "There is always something new to learn in software and coding. It's an ever-changing field and I am happy to become a part of it."
// ];

export default bio;
